const pets = [
    {
        id: 1,
        name: "Buddy",
        type: "other",
        breed: "Capybara",
        age: "2 years old",
        gender: "Male",
        status: "available",
        description: "Friendly and energetic, loves sunbathing.",
        image: "img/Capybara.jpg",
        arrivalDate: "2024-12-15"
    },
    {
        id: 2,
        name: "Luna",
        type: "cat",
        breed: "Siamese Mix",
        age: "1 year old",
        gender: "Female",
        status: "adopted",
        description: "Gentle and affectionate, enjoys cuddling.",
        image: "img/cat.jpg",
        arrivalDate: "2023-03-10",
        adoptionDate: "2025-04-20",
        adopter: "Jorge Jocson"
    },
    {
        id: 3,
        name: "Rocky",
        type: "cat",
        breed: "Ragdoll",
        age: "2 months old",
        gender: "Male",
        status: "available",
        description: "Calm and loyal, great with kids.",
        image: "img/cat2.jpg",
        arrivalDate: "2025-04-15"
    },
    {
        id: 4,
        name: "Sean",
        type: "dog",
        breed: "Labrador",
        age: "3 years",
        gender: "Male",
        status: "available",
        description: "Noisy and fun, loves to run around.",
        image: "img/dog.jpg",
        arrivalDate: "2024-12-20",
    },
    {
        id: 5,
        name: "Croks",
        type: "dog",
        breed: "Shih Tzu",
        age: "3 years",
        gender: "Female",
        status: "adopted",
        description: "Playful and curious, loves chasing toys.",
        image: "img/dog2.jpg",
        arrivalDate: "2023-02-15",
        adoptionDate: "2023-04-10",
        adopter: "Katherine Song Covey"
    },
    {
        id: 6,
        name: "Whitey",
        type: "other",
        breed: "Hamster",
        age: "6 months old",
        gender: "Female",
        status: "available",
        description: "Tiny and energetic, loves running on its wheel and hoarding snacks!",
        image: "img/hamster.jpg",
        arrivalDate: "2025-02-14",
    },
    {
        id: 7,
        name: "Puwa",
        type: "other",
        breed: "Monkey",
        age: "3 years",
        gender: "Female",
        status: "adopted",
        description: "Adorable and quick, enjoys tunneling and cheek-stuffing adventures.",
        image: "img/monkey.jpg",
        arrivalDate: "2025-03-15",
        adoptionDate: "2025-04-05",
        adopter: "Oliver Cedric"
    },
    {
        id: 8,
        name: "Hauie",
        type: "other",
        breed: "Hamster",
        age: "1 year old",
        gender: "Male",
        status: "adopted",
        description: "Cute and mischievous, loves climbing tubes and hiding sunflower seeds.",
        image: "img/rabbit.jpg",
        arrivalDate: "2024-12-03",
        adoptionDate: "2024-12-20",
        adopter: "Shua Lee"
    }
];